### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by visch** [AutoIDM/tap-zohosprints#3]
- [ ] CI
- [ ] POC (0.0.1)
- [ ] POC (0.1.1) - 5 more streams
- [ ] 1.0.0 Release - All Streams, with Discovery and everything
- [ ] Rate Limiting
- [ ] Error Handling
- [ ] Testing with actual data
- [ ] Be sure documentation is clear (Should happen along the way)
- [ ] Add MIT License
- [ ] Release 1.0.0 to PyPi 
- [ ] Submit to Meltano Hub
